# Generated by Django 2.2.12 on 2021-02-24 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Burger_king',
            new_name='BurgerKing',
        ),
    ]
